[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[[redirects]]
  from = "/student-scores/*"
  to = "https://go-backend-rc59.onrender.com/student-scores/:splat"
  status = 200
  force = true
