// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/student-scores": {
            "get": {
                "description": "Returns student score based on registration number (SBD)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-scores"
                ],
                "summary": "Get student score by SBD",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student Registration Number",
                        "name": "sbd",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StudentScore"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/student-scores/report": {
            "get": {
                "description": "Returns an aggregated report of scores by subject",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-scores"
                ],
                "summary": "Get score report by subject",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StudentScore"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/student-scores/top-10-groupA": {
            "get": {
                "description": "Returns the top 10 students in Group A based on their scores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-scores"
                ],
                "summary": "Get top 10 scores for Group A",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StudentScore"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.StudentScore": {
            "type": "object",
            "properties": {
                "diaLi": {
                    "type": "number"
                },
                "gdcd": {
                    "type": "number"
                },
                "hoaHoc": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "lichSu": {
                    "type": "number"
                },
                "maNgoaiNgu": {
                    "type": "string"
                },
                "ngoaiNgu": {
                    "type": "number"
                },
                "nguVan": {
                    "type": "number"
                },
                "sbd": {
                    "type": "string"
                },
                "sinhHoc": {
                    "type": "number"
                },
                "toan": {
                    "type": "number"
                },
                "vatLi": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "go-backend-rc59.onrender.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GoldenOwl Student Score API",
	Description:      "This is an API for student score management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
